# Generated by Django 5.1.7 on 2025-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('SUPER_AGENT', 'Super Agent'), ('MANAGER', 'Manager')], default='AGENT', max_length=15),
        ),
    ]
