# Generated by Django 5.1.7 on 2025-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de lignes'),
        ),
    ]
